In [36]:
import pandas as pd
import numpy as np
import json
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('student_depression_dataset.csv')

print("Initial shape:", df.shape)
df.head()

Initial shape: (27901, 18)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [37]:
if 'id' in df.columns:
    df = df.drop(columns=['id'])

df['Financial Stress'] = pd.to_numeric(df['Financial Stress'], errors='coerce')
df['Financial Stress'] = df['Financial Stress'].fillna(df['Financial Stress'].median())

df['Sleep Duration'] = df['Sleep Duration'].astype(str).str.replace("'", "")
df['Dietary Habits'] = df['Dietary Habits'].astype(str).str.replace("'", "")

In [38]:
category_mappings = {}

binary_map = {'Yes': 1, 'No': 0}
df['Have you ever had suicidal thoughts ?'] = df['Have you ever had suicidal thoughts ?'].map(binary_map)
df['Family History of Mental Illness'] = df['Family History of Mental Illness'].map(binary_map)
category_mappings['Have you ever had suicidal thoughts ?'] = binary_map
category_mappings['Family History of Mental Illness'] = binary_map

sleep_map = {
    'Less than 5 hours': 0,
    '5-6 hours': 1,
    '7-8 hours': 2,
    'More than 8 hours': 3
}
diet_map = {
    'Unhealthy': 0,
    'Moderate': 1,
    'Healthy': 2
}

df['Sleep Duration'] = df['Sleep Duration'].map(sleep_map)
df['Dietary Habits'] = df['Dietary Habits'].map(diet_map)
category_mappings['Sleep Duration'] = sleep_map
category_mappings['Dietary Habits'] = diet_map


df = df.dropna()

le = LabelEncoder()
categorical_cols = ['Gender', 'City', 'Profession', 'Degree']

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
    mapping_dict = dict(zip(le.classes_.astype(str), range(len(le.classes_))))
    category_mappings[col] = mapping_dict

In [41]:
with open('category_mappings.json', 'w') as f:
    json.dump(category_mappings, f, indent=4)

df.to_csv('processed_data.csv', index=False)

print("Data cleaned, encoded, and saved.")
print("\nFinal Data Types:")
print(df.dtypes)

Data cleaned, encoded, and saved.

Final Data Types:
Gender                                     int64
Age                                      float64
City                                       int64
Profession                                 int64
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                           float64
Dietary Habits                           float64
Degree                                     int64
Have you ever had suicidal thoughts ?      int64
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness           int64
Depression                                 int64
dtype: object

In [42]:
df = pd.read_csv('processed_data.csv')
df.head()

,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,51,12,5.0,0.0,8.97,2.0,0.0,1.0,2.0,4,1,3.0,1.0,0,1
1,0,24.0,5,12,2.0,0.0,5.90,5.0,0.0,1.0,1.0,11,0,3.0,2.0,1,0
2,1,31.0,44,12,3.0,0.0,7.03,5.0,0.0,0.0,2.0,6,0,9.0,1.0,1,0
3,0,28.0,49,12,3.0,0.0,5.59,2.0,0.0,2.0,1.0,8,1,4.0,5.0,1,1
4,0,25.0,18,12,4.0,0.0,8.13,3.0,0.0,1.0,1.0,17,1,1.0,1.0,0,0